name: Generate Documentation

on:
  push:
    branches:
      - main # Cambia se il tuo branch principale si chiama 'master'
      - bugfixing_pipeline

permissions:
  contents: write # Fondamentale per il deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # Genera la documentazione usando il tuo script e il config jsdoc.json
      - name: Build Docs
        run: npm run docs

      # Deploy della cartella 'docs-output' sul branch 'gh-pages'
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-output
          branch: gh-pages